tap "1password/tap"
tap "aws/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"

## Programming languages
brew "go"
brew "gopls"
brew "node"
brew "python@3.12"

## IDE with tools
#brew "ipython"
brew "neovim"
brew "yamllint"
brew "shellcheck"
brew "staticcheck"
brew "hadolint"
brew "pre-commit"
brew "git"
brew "git-secrets"
#brew "git-vendor"
# Sort Python imports automatically
brew "isort"
brew "iredis"
brew "jq"
cask "zed"
brew "argo"
brew "gnupg"

## Ansible
brew "ansible"
brew "ansible-lint"
brew "ansible-language-server"
brew "molecule"

## Hashicorp tools: terraform, packer
brew "terraform"
brew "hashicorp/tap/terraform-ls"
brew "terraform-docs"
brew "terraformer", args: ["HEAD"]
brew "terragrunt"
brew "terrascan"
brew "tfk8s"
brew "tflint"
brew "tfsec"
brew "hashicorp/tap/packer"
#brew "localstack"
brew "minamijoyo/hcledit/hcledit"
#brew "inframap"

## Pulumi
brew "pulumi"

## Clouds
brew "awscli"
cask "yandex-cloud-cli"
brew "infracost"

#cask "aws-vault"

## Kubernetes
brew "kubernetes-cli"
brew "krew"
brew "kubectx"
brew "k9s"
cask "lens"
brew "helm"
brew "chart-testing"
brew "minikube"
# Command-line interactive controller for Kubernetes: REPL for to manage a large number of Kubernetes clusters/objects quickly and efficiently
#brew "click"

## GitHub
cask "github"
brew "gh"
# Running GitHub Actions locally
brew "act"

## Docker
brew "dive"

brew "asciinema"
brew "bash-completion"
brew "fontconfig"

brew "cmake"
brew "coreutils"
brew "gnutls"

## Utils
# Simple, fast and user-friendly alternative to find
#brew "fd"
# Ping, but with a graph
brew "gping"
# Calculate various network masks, etc. from a given IP address
brew "ipcalc"
cask "zerotier-one"
cask "drawio"

brew "fish"

brew "graphviz"
brew "lftp"
brew "markdown"
#brew "mkcert"
brew "mtr"
brew "mysql-client"
#brew "newrelic-cli"
brew "nghttp2"
brew "nmap"
brew "nss"
brew "pigz"
brew "pipenv"
brew "pwgen"
brew "qrencode"
brew "ripgrep"
brew "telnet"
brew "tmux"
brew "tree"

# Vulnerability scanner for container images, file systems, and Git repos
brew "trivy"

brew "watch"
brew "wget"
cask "1password-cli"
#cask "cyberduck"
cask "dbeaver-community"
#cask "discord"
#cask "font-hack"
cask "itsycal"
#cask "postman"
#cask "redisinsight"
cask "tunnelblick"

## Media
cask "vlc"

## Browsers
cask "firefox"

## shell
brew "zsh-completion"
brew "zsh"
brew "zsh-autosuggestions"

#brew "hurl"

cask "raycast"

cask "vnc-viewer"

brew "openconnect"
brew "hurl"

cask "vnc-viewer"

# Security
brew "sops"
